service: ${self:custom.product}-${self:custom.component}

frameworkVersion: '>=3.0.0 <4.0.0'

plugins:
  - serverless-plugin-git-variables
  - '@walery/serverless-plugin-stencil'

provider:
  name: aws
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'staging'}
  profile: ${opt:aws-profile, 'sandbox'}
  deploymentBucket:
    name: ${stencil(product-bucket):name}
  deploymentPrefix: ${stencil(product-bucket):deploymentPrefix}
  stackTags:
    Env: ${self:provider.stage}

custom:
  product: run-db-procedures
  component: gha-access

resources:
  - ${stencil(2iq):description}

  - Mappings:
      SecurityGroupMap:
        staging: sg-0ffbaf30dac3cc34f
        prod: sg-999999999999999

    Resources:
      AuthorizeAndRevokeDBAccessPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
          ManagedPolicyName: !Sub ${AWS::StackName}-run-db-procedures
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AuthorizeAndRevokeDBAccess
                Effect: Allow
                Action:
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                Resource:
                  - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/${sgId}
                  - sgId: !FindInMap [SecurityGroupMap, ${self:provider.stage}]

      GitHubActionRole:
        Type: AWS::IAM::Role
        Properties:
          RoleName: ${self:service}-${self:provider.stage}
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Federated: ${cf(us-east-1):oidc-github-global.ActionsOidcProvider}
                Action:
                  - sts:AssumeRoleWithWebIdentity
                Condition:
                  ForAllValues:StringLike:
                    token.actions.githubusercontent.com:aud: sts.amazonaws.com
                    token.actions.githubusercontent.com:sub: repo:${stencil(account):companyName}/${self:custom.product}:*
          ManagedPolicyArns:
            - !Ref AuthorizeAndRevokeDBAccessPolicy
